const field=(name,label,placeholder,options='')=>`<label><span>${label}</span><input name="${name}" type="number" ${options.includes('step=')?'':'step="any"'} placeholder="예: ${placeholder}" required ${options}></label>`;
const dateField=(name,label)=>`<label><span>${label}</span><input name="${name}" type="date" required></label>`;
const commonDates={
  type:'weekdays',title:'주말·지정 휴일을 제외한 일수',
  intro:'프로젝트나 시험 준비에 쓸 평일 수를 계산합니다. 시작일·종료일 포함 기준을 선택하고, 제외할 공휴일이나 휴가일은 직접 적어 주세요.',
  fields:dateField('start','시작일')+dateField('end','종료일')+'<label><span>시작일 포함</span><select name="includeStart"><option value="yes">포함</option><option value="no">제외</option></select></label><label><span>종료일 포함</span><select name="includeEnd"><option value="yes">포함</option><option value="no">제외</option></select></label><label class="workbench-wide"><span>추가로 제외할 날짜 (선택, 쉼표로 구분)</span><input name="holidays" type="text" placeholder="예: 2026-09-24, 2026-09-25"></label>',
  button:'사용 가능한 평일 계산',note:'토요일·일요일을 제외합니다. 공휴일 자동 조회는 제공하지 않으며, 주말에 겹치거나 반복 입력한 휴일은 이중 차감하지 않습니다. 법정 기한이나 회사의 영업일 판정 용도로 확정할 수 없습니다.'
};
const configurations={
  discount:{type:'discount',title:'중복 할인·쿠폰 적용 순서',intro:'20% 할인에 10% 추가 할인이 붙으면 합계 30% 할인이 아닙니다. 할인 단계별 금액과 배송비를 포함한 최종 결제액을 확인하세요.',fields:field('price','정가(원)','100000','min="0.01"')+field('first','첫 할인율(%)','20','min="0" max="100"')+field('second','추가 할인율(%)','10','min="0" max="100"')+field('coupon','추가 정액 쿠폰(원)','5000','min="0"')+field('shipping','배송비(원)','3000','min="0"'),button:'최종 결제액 계산',note:'첫 할인 → 추가 할인 → 정액 쿠폰 → 배송비 순서로 계산합니다. 없는 할인·쿠폰·배송비에는 0을 입력하세요. 쿠폰은 남은 상품가까지만 적용합니다. 쇼핑몰의 할인 순서·중복 허용 조건·원 단위 처리에 따라 실제 결제액은 달라질 수 있습니다.'},
  percent:{type:'points',title:'퍼센트와 퍼센트포인트 비교',intro:'비율이 20%에서 25%로 바뀌면 차이는 5%p, 상대 증가율은 25%입니다. 보고서에서 혼동하기 쉬운 두 값을 한 번에 확인하세요.',fields:field('before','이전 비율(%)','20','min="0" max="100"')+field('after','이후 비율(%)','25','min="0" max="100"'),button:'비율 변화 비교',note:'비율 자체의 차이는 이후 비율 − 이전 비율입니다. 상대 변화율은 그 차이를 이전 비율로 나눕니다. 이전 비율이 0%이면 상대 변화율은 정의되지 않습니다.'},
  'percent-change':{type:'points',title:'비율 변화의 %p 확인',intro:'전환율·점유율처럼 두 비율을 비교할 때, 퍼센트포인트 차이와 상대 변화율을 구분해 표시합니다.',fields:field('before','이전 비율(%)','20','min="0" max="100"')+field('after','이후 비율(%)','25','min="0" max="100"'),button:'퍼센트포인트 계산',note:'예: 20% → 25%는 +5%p이며 기존 비율에 비해서는 +25%입니다. 이전 값이 0%이면 상대 변화율을 계산할 수 없습니다.'},
  'd-day':commonDates,date:{...commonDates,title:'두 날짜 사이의 평일 수'},'exam-dday':{...commonDates,title:'시험 전 확보할 수 있는 평일 수'},'day-count':{...commonDates,title:'주말과 직접 지정한 휴일 제외'},
  'running-pace':{type:'pace',title:'목표 페이스별 거리 통과 시간',intro:'1km 목표 페이스를 정하고 5km·10km·하프·마라톤 거리의 통과 시간을 확인하세요. 같은 페이스를 끝까지 유지한다는 단순 가정입니다.',fields:field('minutes','1km당 분','6','min="0" step="1"')+field('seconds','추가 초','0','min="0" max="59" step="1"'),button:'거리별 예상 시간 보기',note:'거리 × 1km 소요 시간으로 계산하며 초 단위로 반올림합니다. 휴식·오르막·후반 페이스 저하는 반영하지 않아 완주 예측이나 훈련 처방으로 사용할 수 없습니다.'},
  'average-score':{type:'score',title:'평균 뒤에 있는 점수 분포',intro:'평균이 같아도 점수의 편차는 다를 수 있습니다. 입력한 점수의 중앙값·최저·최고·표준편차와 점수대별 인원을 함께 확인하세요.',fields:'<label class="workbench-wide"><span>100점 만점 점수 (쉼표 또는 공백으로 구분)</span><textarea name="scores" rows="3" required placeholder="예: 60, 70, 80, 90, 100"></textarea></label>',button:'점수 분포 분석',note:'입력한 점수 전체를 모집단으로 보고 분산을 개수 N으로 나눕니다. 학교의 성적 산정 방식이나 등급 판정과는 별개인 기술통계입니다. 최대 500개까지 분석합니다.'},
  'break-even':{type:'saleProfit',title:'할인 판매가 손익에 미치는 영향',intro:'할인 행사를 하면 같은 판매량에서 이익이 얼마나 줄어들까요? 할인 전 이익을 유지하려면 필요한 판매량도 함께 확인하세요.',fields:field('fixed','같은 기간의 고정비(원)','1000000','min="0"')+field('units','같은 기간의 예상 판매량(개)','100','min="1" step="1"')+field('price','할인 전 개당 판매가(원)','20000','min="0.01"')+field('variable','개당 변동비(원)','8000','min="0"')+field('discount','행사 할인율(%)','10','min="0" max="100"'),button:'할인 전후 손익 비교',note:'고정비와 개당 변동비가 유지된다는 가정입니다. 같은 수량의 이익 차이와 할인 후 손익분기 수량을 표시하며, 이익 유지 수량은 정수로 올림합니다. 모든 금액의 세금 포함 기준을 맞추고 반품·수량별 원가 변동은 따로 검토하세요.'},
  'fuel-cost':{type:'fuel',title:'주유 예산으로 갈 수 있는 거리',intro:'정해진 주유 예산과 차량 연비로 확보할 수 있는 연료량과 예상 주행거리를 역산합니다. 주유 전에 넣을 금액을 정할 때 쓸 수 있습니다.',fields:field('budget','주유 예산(원)','50000','min="0.01"')+field('efficiency','예상 연비(km/L)','12','min="0.01"')+field('price','리터당 유가(원/L)','1700','min="0.01"'),button:'예상 주행거리 계산',note:'예산 ÷ 리터당 가격 × 연비를 계산합니다. 탱크 잔량·공회전·정체·계절별 연비 차이는 반영하지 않습니다. 실제 주행 가능 거리 표시와는 차이가 있습니다.'},
  margin:{type:'priceTarget',title:'목표 마진율에 맞는 판매가 역산',intro:'원가·배송·포장·건당 광고비를 합친 비용과 판매가에 비례하는 수수료를 입력해 목표 이익률에 필요한 판매가를 찾습니다.',fields:field('cost','건당 총비용(원)','30000','min="0"')+field('fee','판매가 기준 수수료율(%)','10','min="0" max="99.99"')+field('margin','판매가 기준 목표 마진율(%)','20','min="0" max="99.99"'),button:'필요 판매가 계산',note:'판매가 = 건당 총비용 ÷ (1 − 수수료율 − 목표 마진율)입니다. 모든 금액은 같은 세금 포함/제외 기준으로 맞추세요. 부가세·환불·구간별 수수료는 이 역산식에 추가 계산되지 않습니다.'}
};
export function workbenchMarkup(slug){
  const config=configurations[slug];if(!config)return '';
  return `<section class="workbench" data-workbench="${config.type}" aria-labelledby="workbench-${slug}"><h2 id="workbench-${slug}">${config.title}</h2><p>${config.intro}</p><form><div class="workbench-form">${config.fields}</div><button type="submit" class="primary-btn">${config.button}</button></form><div class="result workbench-output" aria-live="polite" aria-atomic="true"></div><p>${config.note}</p></section>`;
}
export const workbenchSlugs=Object.keys(configurations);
